Update pr_check.yml

diff --git a/.github/workflows/pr_check.yml b/.github/workflows/pr_check.yml
--- a/.github/workflows/pr_check.yml
+++ b/.github/workflows/pr_check.yml
@@ -10,22 +10,25 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v4
         with:
-          fetch-depth: 20
+          fetch-depth: 100
 
       - name: Calcualte diff
         run: |
-          echo "Fetching base branch: ${{ github.event.pull_request.base.ref }}"
-          git fetch --no-tags --depth=1 origin +refs/heads/${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}
-          echo "Finding merge-base with origin/${{ github.event.pull_request.base.ref }}..."
-          BASE=$(git merge-base HEAD origin/${{ github.event.pull_request.base.ref }}) || {
-            echo "::error ::Unable to compute merge base. Please rebase your branch on top of '${{ github.event.pull_request.base.ref }}'."
-            exit 1
-          }
-
-          echo "Merge base found: $BASE"
-          echo "Calculating diff between $BASE and HEAD"
+          # echo "Fetching base branch: ${{ github.event.pull_request.base.ref }}"
+          # git fetch --no-tags --depth=1 origin +refs/heads/${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}
+          # echo "Finding merge-base with origin/${{ github.event.pull_request.base.ref }}..."
+          # BASE=$(git merge-base HEAD origin/${{ github.event.pull_request.base.ref }}) || {
+          #   echo "::error ::Unable to compute merge base. Please rebase your branch on top of '${{ github.event.pull_request.base.ref }}'."
+          #   exit 1
+          # }
+          # echo "Merge base found: $BASE"
+          # echo "Calculating diff between $BASE and HEAD"
+          # git diff --name-only $BASE HEAD > changes.txt
+          git fetch origin master
+          BASE=$(git merge-base HEAD origin/master)
+          echo "Changed files (from merge-base $BASE to HEAD):"
           git diff --name-only $BASE HEAD > changes.txt
-   
+
       - name: Display changes
         run: |
           echo "--- Changed files ---"
