Update pr_check.yml

diff --git a/.github/workflows/pr_check.yml b/.github/workflows/pr_check.yml
--- a/.github/workflows/pr_check.yml
+++ b/.github/workflows/pr_check.yml
@@ -9,14 +9,21 @@ jobs:
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
-
-      - name: Fetch master branch
+      - name: Fetch base branch safely
         run: |
           git fetch --no-tags --depth=1 origin +refs/heads/${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }} 2>&1 | tee fetch.log
-          BASE=$(git merge-base HEAD origin/${{ github.event.pull_request.base.ref }})
-          echo "Merge base: $BASE"
-          git diff --name-only $BASE HEAD > changes.txt
+          if grep -q "fatal" fetch.log; then
+            echo "Fetch failed"
+            exit 1
+          fi
+          cat tee fetch.log
+      # - name: Fetch master branch
+      #   run: |
+      #     git fetch --no-tags --depth=1 origin +refs/heads/${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }} 2>&1 | tee fetch.log
+      #     BASE=$(git merge-base HEAD origin/${{ github.event.pull_request.base.ref }})
+      #     echo "Merge base: $BASE"
+      #     git diff --name-only $BASE HEAD > changes.txt
 
-      - name: Display changes
-        run: |
-           cat changes.txt
+      # - name: Display changes
+      #   run: |
+      #      cat changes.txt
